package entities

import "time"

// updated_at and created_at is automatically generated by gorm
type APIKey struct {
	ID          uint       `json:"id" gorm:"primaryKey"`
	UserID      uint       `json:"user_id" gorm:"not null"`
	APIKey      string     `json:"api_key" gorm:"uniqueIndex"` // sudah dalam bentuk hash atau token random
	Description string     `json:"description" gorm:"type:text;default:null"`
	IsActive    bool       `json:"is_active" gorm:"default:true"`
	CreatedAt   time.Time  `json:"created_at" gorm:"autoCreateTime"`
	ExpiredAt   *time.Time `json:"expired_at" gorm:"autoUpdateTime"`

	User User `gorm:"foreignKey:UserID"`
}

// tablename
func (APIKey) TableName() string {
	return "api_keys"
}
