### Variables untuk Telegram Bot API
@baseUrl = {{$dotenv baseUrl}}
@apiVersion = {{$dotenv apiVersion}}

@apiKey = {{$dotenv apiKey}}


### get user telegram by user ID
GET {{baseUrl}}/{{apiVersion}}/telegram
Content-Type: application/json
X-API-Key: {{apiKey}}


### create new user telegram
POST {{baseUrl}}/{{apiVersion}}/telegram
Content-Type: application/json
X-API-Key: {{$dotenv apiKey}}

{
    "telegram_id": 1234567891,
    "username": "nyuuk",
    "first_name": "Nyuuk",
    "last_name": "Nyuuk"
}

### get all user telegram  by user active now
GET {{baseUrl}}/{{apiVersion}}/telegram
Content-Type: application/json
X-API-Key: {{$dotenv apiKey}}


### delete user telegram by telegram ID
DELETE {{baseUrl}}/{{apiVersion}}/telegram/1234567891
Content-Type: application/json
X-API-Key: {{apiKey}}